name: Build C++ EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compile C++
        run: cl /EHsc "okta c++.cpp" /Fe:program.exe

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: program-exe
          path: program.exe
